### ISSUE TITLE
How would you change your approach to use GL_TRIANGLES instead of GL_TRIANGLE_STRIP

### ISSUE THREAD

**Issue by richardba** [paanil/planet#1]
I have been accompanying and using this render, and it uses GL_TRIANGLES_STRIP. I'm trying to adapt it to use tessellation shader, but I'm unable to set it up properly because the way triangles are indexed just half of them is sent to the GPU considering the patch primitive.

Could you please enlight me on what changes would be made to duplicate the number of vertices needed to comply with GL_PATCHES,3 primitive?

**Comment by richardba** [comment]
@paanil ?

**Comment by paanil** [comment]
I'm not familiar with tessellation shader. But if you wish to convert from triangle strip to bare triangles, you could either generate the correct indices straight away, or just iterate the indices of the triangle strip and generate new indices based on those. Something like (pseudo code):
`
for i in range(2, triangle_strip_index_count):
    index0 = triangle_strip_indices[i-2]
    index1 = triangle_strip_indices[i-1]
    index2 = triangle_strip_indices[i]
    add_triangle(index0, index1, index2)
`
Just remember to change the winding for every other triangle, and skip degenerates.

**Comment by richardba** [comment]
how exactly that would be done in your approach?
